export {
    FETCH_CHARACTER_START,
    FETCH_CHARACTER_SUCCESS,
    FETCH_CHARACTER_FAILURE,
    FETCH_SPELLS_START,
    FETCH_SPELLS_SUCCESS,
    FETCH_SPELLS_FAILURE,
    FETCH_HOUSES_START,
    FETCH_HOUSES_SUCCESS,
    FETCH_HOUSES_FAILURE,
    FETCH_SORTING_START,
    FETCH_SORTING_SUCCESS,
    FETCH_SORTING_FAILURE,
    getCharacters,
    getSpells,
    getHouses,
    getSortingHat
} from "./actions.js"